### ISSUE TITLE
Enable Ruby completion

### ISSUE THREAD

**Issue by Toshiki-670** [Toshiki-670/dotfiles#3]
https://qiita.com/nrk_baby/items/154e3fa15c48a39e3375
Shougo/deoplete-rct
fishbullet/deoplete-ruby
osyo-manga/vim-monster

これらのプラグインが有効かもしれない。参考にしたサイトは一年以内のもの。
deopleteを使った補完を実現したい。

**Comment by toshiki-rlearning** [comment]
gem install solargraph で運用する

**Comment by toshiki-rlearning** [comment]
uplus/deoplete-solargraph も良さそう
ただし、Neovim推奨になっているがVim8に対応しているかどうか確かめる必要がある。
